create table videos(
id int primary key auto_increment,
name varchar(50) not null,
constraint unique_video_name unique(name),
display_name varchar(50) not null,
url varchar(50) not null,
constraint unique_url unique(url),
duration time,
tags varchar(100) not null,
status bit(1),
description text,
transcript varchar(50),
created_by varchar(50) not null,
created_on timestamp not null default current_timestamp,
modified_by varchar(50),
modified_on default null on update current_timestamp,
category_id int not null,
level_id int not null,
constraint fk_videos_category_id foreign key(category_id) references categories(id),
constraint fk_videos_level_id foreign key(level_id) references levels(id)
);
